---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno-image-verification-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-image-verification-service
  namespace: kyverno-image-verification-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno-image-verification-service-role
  namespace: kyverno-image-verification-service
rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kyverno-image-verification-service-rolebinding
  namespace: kyverno-image-verification-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kyverno-image-verification-service-role
subjects:
  - kind: ServiceAccount
    name: kyverno-image-verification-service
    namespace: kyverno-image-verification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kyverno-image-verification-service
  name: kyverno-image-verification-service
  namespace: kyverno-image-verification-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kyverno-image-verification-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kyverno-image-verification-service
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsNonRoot: true
      containers:
        - image: ghcr.io/kyverno/image-verification-service:latest
          imagePullPolicy: Always
          name: kyverno-image-verification-service
          args:
            - --leader-elect=false
          # USE FOR PRIVATE IMAGES
          # - --imagePullSecrets=regcred
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 32Mi
              cpu: 100m
          securityContext:
            runAsUser: 2000
            runAsGroup: 3000
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: svc
            - name: DEPLOYMENT_NAME
              value: kyverno-image-verification-service
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POLICY_DIR
              value: policies
          volumeMounts:
            - name: notation
              mountPath: /notation
      volumes:
        - name: policies
          image:
            reference: ghcr.io/vishal-chdhry/ivpol:latest
      serviceAccountName: kyverno-image-verification-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kyverno-image-verification-service
  name: svc
  namespace: kyverno-image-verification-service
spec:
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: 9443
  selector:
    app: kyverno-image-verification-service
