apiVersion: v1
kind: Service
metadata:
  name: {{ template "kyverno-image-verification-service.serviceName" . }}
  namespace: {{ template "kyverno-image-verification-service.namespace" . }}
  labels:
    {{- include "kyverno-image-verification-service.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "kyverno-image-verification-service.matchLabels.common" . | nindent 4 }}
