{{ range $name, $secret := .Values.deployment.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ template "nirmata-image-compliance.namespace" $ }}
  labels:
    {{- include "nirmata-image-compliance.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "nirmata-image-compliance.config.imagePullSecret" $secret }}
{{ end }}
