apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "nirmata-image-compliance.roleName" . }}binding
  namespace: {{ template "nirmata-image-compliance.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "nirmata-image-compliance.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "nirmata-image-compliance.serviceAccountName" . }}
  namespace: {{ template "nirmata-image-compliance.namespace" . }}
