apiVersion: v1
kind: Service
metadata:
  name: {{ template "nirmata-image-compliance.serviceName" . }}
  namespace: {{ template "nirmata-image-compliance.namespace" . }}
  labels:
    {{- include "nirmata-image-compliance.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      name: https
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "nirmata-image-compliance.matchLabels.common" . | nindent 4 }}
