apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nirmata-image-compliance.serviceAccountName" . }}
  namespace: {{ template "nirmata-image-compliance.namespace" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
