# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Lint

permissions: {}

on:
  push:
    branches:
      - 'main'
      - 'release*'
  pull_request:
    branches:
      - 'main'
      - 'release*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4696ba8babb6127d732c3c6dde519db15edab9ea # v3.7.1
        with:
          version: v1.54.2
          skip-cache: true
      - name: go fmt check
        run: make fmt
      - name: go vet check
        run: make vet
