name: Unit Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup build env
        uses: ./.github/actions/setup-build-env
        with:
          build-cache-key: tests
      - name: Unit test
        run: make test-unit
